import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {createClient} from "next-sanity";

const inter = Inter({subsets: ['latin']})

const client = createClient({
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATASET,
  token: process.env.SANITY_TOKEN,
  apiVersion: "2022-03-25",
  useCdn: true
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}

export async function getStaticPaths() {
  // const pages = await client.fetch(`*[_type == "page"]{_id,_rawSlug,language,alternativePages}`);
  return {
    paths: [{params: {slug: 'a'}}, {params: {slug: 'b'}}],
    fallback: false, // can also be true or 'blocking'
  }
}

export async function getStaticProps(context) {
  // const pages = await client.fetch(`*[_type == "page"]{_id,_rawSlug,language,alternativePages{language,_rawSlug}}`);
  return {
    props: {}, // will be passed to the page component as props
  }
}
